branch-protection:
  orgs:
    jenkins-x:
      protect: true
      required_status_checks:
        contexts:
        - serverless-jenkins
      repos:
        jx:
          restrictions:
            users: []
        dex:
          restrictions:
            users: []
        ext-jacoco:
          restrictions:
            users: []     
    jenkins-x-charts:
      protect: true
      required_status_checks:
        contexts:
        - knative-build
      repos:
        vault-operator:
          restrictions:
            users: []
owners_dir_blacklist:
  default: null
  repos: null
prowjob_namespace: jx
pod_namespace: jx
push_gateway: {}
sinker:
  resync_period: 4m
  max_prowjob_age: 24h
  max_pod_age: 24h
postsubmits:
  jenkins-x/jx:
  - agent: knative-build
    branches:
    - master
    build_spec:
      serviceAccountName: jenkins
      steps:
      - env:
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: XDG_CONFIG_HOME
          value: /home/jenkins
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker/
        - name: DOCKER_REGISTRY
          valueFrom:
            configMapKeyRef:
              key: docker.registry
              name: jenkins-x-docker-registry
        image: jenkinsxio/jenkins-go:dev_18
        name: "release"
        resources:
          limits:
            cpu: 3
            memory: 4Gi
          requests:
            cpu: 2
            memory: 3Gi
        volumeMounts:
        - mountPath: /home/jenkins/.docker
          name: jenkins-docker-cfg
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        - mountPath: /root/.m2/
          name: jenkins-maven-settings
        - mountPath: /home/jenkins/.gnupg
          name: jenkins-release-gpg
      volumes:
      - name: jenkins-docker-cfg
        secret:
          secretName: jenkins-docker-cfg
      - hostPath:
          path: /var/run/docker.sock
        name: docker-sock-volume
      - name: jenkins-maven-settings
        secret:
          secretName: jenkins-maven-settings
      - name: jenkins-release-gpg
        secret:
          secretName: jenkins-release-gpg
    name: release
  jenkins-x/jenkins-x-builders:
  - agent: knative-build
    branches:
    - master
    build_spec:
      serviceAccountName: jenkins
      steps:
      - env:
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: XDG_CONFIG_HOME
          value: /home/jenkins
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker/
        - name: DOCKER_REGISTRY
          valueFrom:
            configMapKeyRef:
              key: docker.registry
              name: jenkins-x-docker-registry
        image: jenkinsxio/jenkins-go:dev_18
        name: "release"
        resources:
          limits:
            cpu: 3
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - mountPath: /home/jenkins/.docker
          name: jenkins-docker-cfg
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        - mountPath: /root/.m2/
          name: jenkins-maven-settings
        - mountPath: /home/jenkins/.gnupg
          name: jenkins-release-gpg
      volumes:
      - name: jenkins-docker-cfg
        secret:
          secretName: jenkins-docker-cfg
      - hostPath:
          path: /var/run/docker.sock
        name: docker-sock-volume
      - name: jenkins-maven-settings
        secret:
          secretName: jenkins-maven-settings
      - name: jenkins-release-gpg
        secret:
          secretName: jenkins-release-gpg
    name: release
  jenkins-x/jenkins-x-serverless:
  - agent: knative-build
    branches:
    - master
    build_spec:
      serviceAccountName: jenkins
      steps:
      - env:
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: XDG_CONFIG_HOME
          value: /home/jenkins
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker/
        - name: DOCKER_REGISTRY
          valueFrom:
            configMapKeyRef:
              key: docker.registry
              name: jenkins-x-docker-registry
        image: jenkinsxio/jenkins-cwp:dev_22
        name: "release"
        resources:
          limits:
            cpu: 3
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - mountPath: /home/jenkins/.docker
          name: jenkins-docker-cfg
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        - mountPath: /root/.m2/
          name: jenkins-maven-settings
        - mountPath: /home/jenkins/.gnupg
          name: jenkins-release-gpg
      volumes:
      - name: jenkins-docker-cfg
        secret:
          secretName: jenkins-docker-cfg
      - hostPath:
          path: /var/run/docker.sock
        name: docker-sock-volume
      - name: jenkins-maven-settings
        secret:
          secretName: jenkins-maven-settings
      - name: jenkins-release-gpg
        secret:
          secretName: jenkins-release-gpg
    name: release

  jenkins-x/dex:
  - agent: knative-build
    branches:
    - master
    build_spec:
      serviceAccountName: jenkins
      template:
        name: jenkins
        arguments:
        - name: BUILDER
          value: jenkins-go
    name: release

  jenkins-x/ext-jacoco:
  - agent: knative-build
    branches:
    - master
    build_spec:
      serviceAccountName: jenkins
      template:
        name: jenkins
        arguments:
        - name: BUILDER
          value: jenkins-go
    name: release

  rawlingsj/testchart:
  - agent: knative-build
    branches:
    - master
    build_spec:
      serviceAccountName: jenkins
      template:
        name: jenkins
        arguments:
        - name: BUILDER
          value: jenkins-go
    name: release

  jenkins-x-charts/vault-operator:
  - agent: knative-build
    branches:
    - master
    build_spec:
      serviceAccountName: knative-build-bot
      template:
        name: knative-chart-release
        arguments:
        - name: WORKSPACE
          value: /workspace/vault-operator
    name: release

presubmits:
  jenkins-x/jx:
  - agent: knative-build
    always_run: false
    build_spec:
      serviceAccountName: jenkins
      steps:
      - env:
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: XDG_CONFIG_HOME
          value: /home/jenkins
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker/
        - name: DOCKER_REGISTRY
          valueFrom:
            configMapKeyRef:
              key: docker.registry
              name: jenkins-x-docker-registry
        image: jenkinsxio/jenkins-go:dev_18
        name: "continuous-integration"
        resources:
          limits:
            cpu: 3
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - mountPath: /home/jenkins/.docker
          name: jenkins-docker-cfg
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        - mountPath: /root/.m2/
          name: jenkins-maven-settings
        - mountPath: /home/jenkins/.gnupg
          name: jenkins-release-gpg
      volumes:
      - name: jenkins-docker-cfg
        secret:
          secretName: jenkins-docker-cfg
      - hostPath:
          path: /var/run/docker.sock
        name: docker-sock-volume
      - name: jenkins-maven-settings
        secret:
          secretName: jenkins-maven-settings
      - name: jenkins-release-gpg
        secret:
          secretName: jenkins-release-gpg
    context: serverless-jenkins
    name: serverless-jenkins
    rerun_command: /test bdd
    trigger: (?m)^/test( all| bdd),?(\s+|$)

  jenkins-x/jenkins-x-builders:
  - agent: knative-build
    always_run: false
    build_spec:
      serviceAccountName: jenkins
      steps:
      - env:
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: XDG_CONFIG_HOME
          value: /home/jenkins
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker/
        - name: DOCKER_REGISTRY
          valueFrom:
            configMapKeyRef:
              key: docker.registry
              name: jenkins-x-docker-registry
        image: jenkinsxio/jenkins-go:dev_18
        name: "continuous-integration"
        resources:
          limits:
            cpu: 3
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - mountPath: /home/jenkins/.docker
          name: jenkins-docker-cfg
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        - mountPath: /root/.m2/
          name: jenkins-maven-settings
        - mountPath: /home/jenkins/.gnupg
          name: jenkins-release-gpg
      volumes:
      - name: jenkins-docker-cfg
        secret:
          secretName: jenkins-docker-cfg
      - hostPath:
          path: /var/run/docker.sock
        name: docker-sock-volume
      - name: jenkins-maven-settings
        secret:
          secretName: jenkins-maven-settings
      - name: jenkins-release-gpg
        secret:
          secretName: jenkins-release-gpg
    context: serverless-jenkins
    name: serverless-jenkins
    rerun_command: /test bdd
    trigger: (?m)^/test( all| bdd),?(\s+|$)
  jenkins-x/jenkins-x-serverless:
  - agent: knative-build
    always_run: false
    build_spec:
      serviceAccountName: jenkins
      steps:
      - env:
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: XDG_CONFIG_HOME
          value: /home/jenkins
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker/
        - name: DOCKER_REGISTRY
          valueFrom:
            configMapKeyRef:
              key: docker.registry
              name: jenkins-x-docker-registry
        image: jenkinsxio/jenkins-cwp:dev_22
        name: "continuous-integration"
        resources:
          limits:
            cpu: 3
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - mountPath: /home/jenkins/.docker
          name: jenkins-docker-cfg
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        - mountPath: /root/.m2/
          name: jenkins-maven-settings
        - mountPath: /home/jenkins/.gnupg
          name: jenkins-release-gpg
      volumes:
      - name: jenkins-docker-cfg
        secret:
          secretName: jenkins-docker-cfg
      - hostPath:
          path: /var/run/docker.sock
        name: docker-sock-volume
      - name: jenkins-maven-settings
        secret:
          secretName: jenkins-maven-settings
      - name: jenkins-release-gpg
        secret:
          secretName: jenkins-release-gpg
    context: serverless-jenkins
    name: serverless-jenkins
    rerun_command: /test bdd
    trigger: (?m)^/test( all| bdd),?(\s+|$)

  jenkins-x/dex:
  - agent: knative-build
    always_run: false
    build_spec:
      serviceAccountName: jenkins
      template:
        name: jenkins
        arguments:
        - name: BUILDER
          value: jenkins-go
    context: serverless-jenkins
    name: serverless-jenkins
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)

  jenkins-x/ext-jacoco:
  - agent: knative-build
    always_run: false
    build_spec:
      serviceAccountName: jenkins
      template:
        name: jenkins
        arguments:
        - name: BUILDER
          value: jenkins-go
    context: serverless-jenkins
    name: serverless-jenkins
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)

  rawlingsj/testchart:
  - agent: knative-build
    always_run: false
    build_spec:
      serviceAccountName: jenkins
      template:
        name: jenkins
        arguments:
        - name: BUILDER
          value: jenkins-go
    context: serverless-jenkins
    name: serverless-jenkins
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)

  jenkins-x-charts/vault-operator:
  - agent: knative-build
    always_run: false
    build_spec:
      template:
        name: knative-chart-ci
        arguments:
        - name: WORKSPACE
          value: /workspace/vault-operator
    context: knative-build
    name: knative-build
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)

tide:
  sync_period: 2m
  status_update_period: 1m
  context_options:
    from-branch-protection: true
  skip-unknown-contexts: false
  queries:
  - labels:
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - jenkins-x-bot/environment-jenkinsx-dev-staging
    - jenkins-x-bot/environment-jenkinsx-dev-production
    - jenkins-x/jx
    - jenkins-x/dex
    - jenkins-x/ext-jacoco
    - jenkins-x/jenkins-x-builders
    - jenkins-x/jenkins-x-serverless
    - jenkins-x-charts/vault-operator
    - rawlingsj/testchart
  target_url: https://deck.jx.cd.jenkins-x.io