branch-protection:
  orgs:
    jenkins-x:
      protect: true
      required_status_checks:
        contexts:
        - jenkins-engine-ci
      repos:
        jx:
          restrictions:
            users: []

owners_dir_blacklist:
  default: null
  repos: null

prowjob_namespace: jx
pod_namespace: jx

heart:
  adorees:
  - jenkins-x-bot

push_gateway: {}

sinker:
  resync_period: 4m
  max_prowjob_age: 48h
  max_pod_age: 30m

postsubmits:
  jenkins-x/jx:
  - agent: knative-build
    branches:
    - master
    build_spec:
      serviceAccountName: jenkins
      steps:
      - env:
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: XDG_CONFIG_HOME
          value: /home/jenkins
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker/
        - name: DOCKER_REGISTRY
          valueFrom:
            configMapKeyRef:
              key: docker.registry
              name: jenkins-x-docker-registry
        image: jenkinsxio/jenkins-go:dev_18
        name: ""
        resources: {}
        volumeMounts:
        - mountPath: /home/jenkins/.docker
          name: jenkins-docker-cfg
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        - mountPath: /root/.m2/
          name: jenkins-maven-settings
        - mountPath: /home/jenkins/.gnupg
          name: jenkins-release-gpg
      volumes:
      - name: jenkins-docker-cfg
        secret:
          secretName: jenkins-docker-cfg
      - hostPath:
          path: /var/run/docker.sock
        name: docker-sock-volume
      - name: jenkins-maven-settings
        secret:
          secretName: jenkins-maven-settings
      - name: jenkins-release-gpg
        secret:
          secretName: jenkins-release-gpg
    name: release
presubmits:
  jenkins-x/jx:
  - agent: knative-build
    always_run: false
    build_spec:
      serviceAccountName: jenkins
      steps:
      - env:
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker/
        - name: DOCKER_REGISTRY
          valueFrom:
            configMapKeyRef:
              key: docker.registry
              name: jenkins-x-docker-registry
        image: jenkinsxio/jenkins-go:dev_18
        name: ""
        resources: {}
        volumeMounts:
        - mountPath: /home/jenkins/.docker
          name: jenkins-docker-cfg
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        - mountPath: /root/.m2/
          name: jenkins-maven-settings
        - mountPath: /home/jenkins/.gnupg
          name: jenkins-release-gpg
      volumes:
      - name: jenkins-docker-cfg
        secret:
          secretName: jenkins-docker-cfg
      - hostPath:
          path: /var/run/docker.sock
        name: docker-sock-volume
      - name: jenkins-maven-settings
        secret:
          secretName: jenkins-maven-settings
      - name: jenkins-release-gpg
        secret:
          secretName: jenkins-release-gpg
    context: jenkins-engine-ci
    name: jenkins-engine-ci
    rerun_command: /test bdd
    trigger: (?m)^/test( all| bdd),?(\s+|$)

tide:
  sync_period: 5m
  status_update_period: 30s
  context_options:
    from-branch-protection: true
  skip-unknown-contexts:
    false
  queries:
  - labels:
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - jenkins-x-bot/environment-jenkinsx-dev-staging
    - jenkins-x-bot/environment-jenkinsx-dev-production
    - jenkins-x/jx
  target_url: https://deck.jx.cd.jenkins-x.io
