triggers:
- repos:
  - jenkins-x/prow-config
approve:
- lgtm_acts_as_approve: true
  repos:
  - jenkins-x-bot/environment-jenkinsx-dev-staging
  - jenkins-x-bot/environment-jenkinsx-dev-production
  review_acts_as_approve: true
blunderbuss: {}
cat: {}
config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
heart:
  adorees:
  - jenkins-x-bot
owners: {}
plugins:
  jenkins-x/prow-config:
  - config-updater
  - size
  - shrug
  - skip
  - yuks
  jenkins-x-bot/environment-jenkinsx-dev-production:
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkins-x-bot/environment-jenkinsx-dev-staging:
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkins-x/jx:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkins-x/jenkins-x-builders:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-serverless:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/vault-operator:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/dex:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  rawlingsj/testchart:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/ext-jacoco:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/ext-java-code-quality:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
requiresig: {}
sigmention: {}
slack: {}
welcome: {}
